### PR TITLE
Fix issue 1086

### PR DESCRIPTION
**Pull request by Cindyli0310**
I fixed the issue by add Geographic Visualization's concept, goals and used tools.

### CODE REVIEW

**Comment by XZou0803** [comment]
Hi, Cindy! I think you should add an "@" in the source.

**Comment by Cindyli0310** [comment]
> Hi, Cindy! I think you should add an "@" in the source.

Hi @XZou0803 ,thanks for letting me know. I already added it.

**Review by XZou0803 — APPROVED** [review]
I like the changes! It helps the reader learn more about Geographic Visualizations.
And I also add this PR to Week 5.

**Comment by Cindyli0310** [comment]
> I like the changes! It helps the reader learn more about Geographic Visualizations.
> And I also add this PR to Week 5.

@XZou0803 Hi, thanks a lot for adding PR to Week 5!

**Pull request merged**
