### PR TITLE
I Fixed the citation issue on #773.

### PR DESCRIPTION
**Pull request by Cindyli0310**
On first week, I mentioned 'Unformatted reference citation' problem. 
This week,I fixed the citation issue by create the link and then add the link in book.bib.

### CODE REVIEW

**Comment by XZou0803** [comment]
Hi Cindy~
The fix is very nice, but it seems there is no file change in Book.bib yet. Did you commit that change?

**Comment by Cindyli0310** [comment]
> Hi Cindy~
> The fix is very nice, but it seems there is no file change in Book.bib yet. Did you commit that change?

**Comment by Cindyli0310** [comment]
> > Hi Cindy~
> > The fix is very nice, but it seems there is no file change in Book.bib yet. Did you commit that change?

**Comment by Cindyli0310** [comment]
> Hi Cindy~
> The fix is very nice, but it seems there is no file change in Book.bib yet. Did you commit that change?

@XZou0803 Hi,thanks for reminding me. I think because I did not put all in one branch, so it caused the issue. I will close this one and redo it again.

**Pull request closed without merging**
