### PR TITLE
Update 3.6.1

### PR DESCRIPTION
**Pull request by btamsir**
Removed 1. "Definition of typeography" since it did not make sense.

### CODE REVIEW

**Comment by ttussing** [comment]
I think we tried merging into master here, we should try for merging into contributions

**Comment by preranap1** [comment]
Just realized we had to make changes to the contributions branch this one is getting merged with the master...

**Comment by preranap1** [comment]
@ttussing looks like you are reading my mind!
@btamsir you may wanna replicate these changes into the contributions branch...

**Comment by btamsir** [comment]
Moved to contributions branch. Thanks for catching that!

**Pull request merged**
