### PR TITLE
military budget: diff btw abs n relative data

### PR DESCRIPTION
**Pull request by syragrg**

### CODE REVIEW

**Comment by syragrg** [comment]
Under 6.4 Data Deception and Graphic Integrity @harizhisham

**Comment by syragrg** [comment]
u can see my PR #1173. Ive provided a link for the image but its better to upload the image instead of providing a link

**Comment by harizhisham** [comment]
dope, i'll approve and merge

**Comment by syragrg** [comment]
xie xie

**Comment by syragrg** [comment]
yea i havent figured it out yet

**Pull request merged**
