### PR TITLE
Tableau features 3.4.7 #753

### PR DESCRIPTION
**Pull request by KlippL**
This is a new section added to 3.4.7 for having multiple data sources in Tableau (as well as 2 new references in the bibliography). 

This references #753

### CODE REVIEW

**Review by Vidya313 — DISMISSED** [review]
A good addition to the Tableau section.

**Review by ttussing — DISMISSED** [review]
Great additions!

**Comment by Vidya313** [comment]
I have expanded the section multiple data sources in Tableau by adding some content on union functionality. The changes are committed to the branch : Tableau-Features-3.4.7-#753

**Comment by rlwy** [comment]
It's great that you changed all the hard coded lists into dynamic HTML lists.

**Comment by mschermann** [comment]
@KlippL I leave this PR open so we can discuss how to resolve conflicts in class.

**Comment by KlippL** [comment]
@mschermann you didn't go over this in class... should we keep working on this branch this week with new tableau content or should we try to figure out how to resolve this and close this branch?

**Comment by mschermann** [comment]
@KlippL There are still unresolved conflicts. Fix them and then merge.

**Comment by mschermann** [comment]
@KlippL @ttussing I fixed the conflicts. Review and merge.

**Review by ttussing — APPROVED** [review]

**Pull request merged**
