### PR TITLE
Added "Is Beauty Important?" Case Study

### PR DESCRIPTION
**Pull request by kthang**
Added a new case study, which examines if beauty is an important consideration when making a visualization.  It is based on this article, by the Senior Tech Evangelist at Tableau

### CODE REVIEW

**Comment by pragyansharma24** [comment]
Hi @kthang : Please commit to the contributions branch. 
Currently, the commit request is for Master.

**Comment by kthang** [comment]
Not sure if that's what you were asking for, but I changed the base branch.

**Comment by jymhe120** [comment]
I like the content of your case study. I think it provides some valuable insight. I would love to see the two images that you added. Would you please upload these two images to the image file of your branch, so we may preview them?

**Comment by kthang** [comment]
@jymhe120 Part of my request was a image upload called which_is_best.png.  It should've been in the image folder.

**Pull request merged**
