### PR TITLE
Added the images for Section 2.1

### PR DESCRIPTION
**Pull request by Kushall-Dayal**
Added missing visual examples for Presentation, Exploratory Analysis, Confirmatory Analysis to images directory
as well as the markdown

### CODE REVIEW

**Comment by srivasud** [comment]
Hi @Kushall-Dayal ,
I see that you have added 3 images. Do you want to add the citation for these images as well?
It will be a good idea to add citation for these images as well.
Thanks,
Srinivasan

**Comment by Kushall-Dayal** [comment]
Hi @srivasud ,
Thanks for pointing that out,I did add the citations

Thanks!

**Comment by Cindyli0310** [comment]
Hi @Kushall-Dayal, thanks a lot for adding images and citations in the article. That is really helpful to reading the page.

**Comment by Kushall-Dayal** [comment]
added images for issue #821

**Pull request merged**
