### PR TITLE
2.2.0.1 Importance of Data Exploration #1034 - 2

### PR DESCRIPTION
**Pull request by kwright76**
I have included some steps of the data exploration process to validate the article I had summarized last week.

### CODE REVIEW

**Review by strivedi2 — DISMISSED** [review]
Good additions!

**Comment by strivedi2** [comment]
@kwright76 The paragraph 'Data Exploration...' is repeated twice. Can you quickly check and remove one of the paragraphs? Other changes look good!

**Review by strivedi2 — CHANGES_REQUESTED** [review]
The paragraph 'Data exploration...' is repeated twice instead of being over written. Other additions look good!

**Comment by syragrg** [comment]
Hi Kyle, the steps aligns with pretty much what we have been doing in class! Thanks for the addition.  When explaining the steps in data exploration, the sentence starting with "Lastly is to..." sounds a little off. Can you make it consistent with the sentence before it and perhaps phrase it "Lastly, grasp knowledge..." or however you see fit :)

**Comment by mschermann** [comment]
@kwright76 Please include the change requests and merge.

**Review by strivedi2 — APPROVED** [review]
Thanks for making the changes!

**Pull request merged**
