### PR TITLE
1304 -rlwy

### PR DESCRIPTION
**Pull request by rlwy**
Updated the unordered list  and bold text formatting for _section 6.1 Important Prerequisites of data visualization project_

Resolve for issue #1304

### CODE REVIEW

**Review by srivasud — CHANGES_REQUESTED** [review]
Hi @rlwy  (Rachael Lee), Sorry to ask you to do further changes.
Since Qing changes were merged before yours, we need to do few more formatting..
For easiness I reformatted the entire section and i tested in a simple .md file in github
(https://github.com/srivasud/threeaspects/blob/master/test.md).
I have pasted the entire contents for you to take a look... 
What I did is following on top of your changes...
a. Assigned Qing's new paragraph a bullet.
b. Moved the tools into a separate paragraph.
c. intended the subsections accordingly.
Is it possible for you to incorporate this in your commit and reraise the PR. This PR has merge conflict..I added a test.md in my repository with the below fix...
https://github.com/srivasud/threeaspects/blob/master/test.md
You can edit the file and copy the contents from there. Let me know if you can do that?


## Important Prerequisites of data visualization project

The below are the important prerequisites of a successful data visualization project.
[@prerequisites_vizhitachi]

+ **Defining the project** Behind every project there is an organizational need. The need could be as simple as a weekly sales performance dashboard or a sophisticated predictive recommendation engine. Addressing these needs with a concrete measurable objectives provide the right framework to deliver the right information in  right fashion. The communication of Key Performance Indicators (KPIs) from the end product is very important for the consumers. To do this, you need to collect requirements, set design processes, schedule regular discussions with users and continue these meetings until the final project rollout. Sample questions that can help one understand the project better:  
    + what is the organization need you are trying to address?  
    + What are the main data sources you need to access?  
    + Is the data upto date or will it provide updated data in regular intervals?  
    + which type of data visual works best?  
    + Is there a measurable goal you want to achieve?  
    + What are the core KPIs to convey to users if any?  
    + Which type of KPI visualization is suitable for this goal?  

+ **Understanding the audience** How will they process this visualization is another important prerequisite. Designing a visualization for scientists is entirely different from a visualization designed for law-makers or for general public. Most user want to see 'Key performance indicators' which are the main drivers for visualizations. The following are different kinds of visualizations that can be used to display KPIs:
    + Quantities: counts or measures. Example - Count of likes or comments
    + Trends and changes over time:  time series. Example - Change in sales quantity over time
    + Relatives Share and proportions:  display relationship between the parts and the whole. Example - breakdown of a stock portfolio by asset.
    + Ranked list: although not a real data visualization, it could achieve the goal needed.
    + Geographical Location: Gives user spatial and physical relationships.

+ **Understanding the data you are trying to visualize** such as shape, dimension of the data, is data a time-series, relationship in data between entities,categorical attributes is also an important prerequisite. Is this data from a single source or multiple sources?. If the data is from multiple sources, they need to be blended together without loosing the meta data constraints and business rules. When the data is collected, the end goal should be kept in mind.

+ **Deciding which visual is best**
One of the biggest challenges for business users is deciding which visual should be used to best represent the information. Tables, Linechart, Areachart, Barchart, Scatterplots, Piechart, Treemaps, Heatmaps, Natual Language Generation, Etc.

+ **Choosing the tool for the project**  
[@prerequisites_tools]  
    Choosing a tool, depends on the person conducting or designing the visualization, and the platform he wants to integrate his work into.It also depends on the ability of the user and their needs. eg:-Tableau has a no code approach whereas D3.js ,Altair etc has coding approaches. These approaches help users to adopt and customize further. For example: With Tableau, users can add customization such as a new formula addition, sorting behaviors to the charts initially developed, whereas D3.js and other coding tools may not give that flexibility and the users are dependent on the designer to make further changes. These approaches are discussed in detail below:  
  + **No coding:** One can start with MS Excel and probably use pivot tables feature, in excel you come up with decent charts. If you already have some data and need a powerful tool to explore the data visually, Tableau is the tool. There is a free public version and a paid version , which students can get for free. One can publish the charts to web .To start Tableau Public website has a good number of examples to take inspiration from.  
  + **Some coding:** If somebody wants to venture in the coding world to build charts, R is a good start. It is easy to learn, free as it is opensource.One can us the ggplot library in R to come up with visual data exploration. You can publish these charts with the help Shiny package and add a bit of interaction as well.  
  + **More coding:** This section is derived because of recent innovation in interactive visualization, especially on the web. One might ask where to start to come up with interactive visualizations as good as New York Times. The answer is D3.js, many of the data visualizations running in the browser today is D3.js, created by Mike Bostock. This does mean you&#39;ll need to learn some Javascript in general and then D3.js specifically. One area to call out as a particular strength of D3 is geospatial visualizations. D3 is great at creating maps of many flavors. Finally, if you really want to learn a do-it-all programming language that just happens to be great at data visualization, go with Python. Python is a general purpose and powerful tool, and it&#39;s quite popular in the data science community. Finally, much like D3.js for Javascript or ggplot for R, there are many Python libraries dedicated to data visualization. Seaborn (which builds on an older popular library, matplotlib) and Bokeh are probably the best-in-class right now, but this is a quickly evolving and improving landscape. Both the [Seaborn](http://stanford.edu/~mwaskom/software/seaborn/examples/index.html) and [Bokeh](http://bokeh.pydata.org/en/latest/docs/gallery.html) websites include galleries showing off the kinds of visualizations you can create with those tools.

**Comment by srivasud** [comment]
The other alternative I have is, approve your PR and do these changes myself and add you and Marvin to the review. Please let me know which ever way works for you, I can go with that!

**Review by srivasud — DISMISSED** [review]
Approving this PR. Since I do not want to hold up this PR. I can do these changes as part of my issue#1231

**Review by srivasud — APPROVED** [review]
@rlwy, I will preserve your changes and will make a PR on top of yours with the changes I pasted above. I will add you to the PR to review.
Approving your PR.

**Comment by rlwy** [comment]
Thanks @srivasud for all the suggestions and also taking over in the remaining changes.

**Pull request merged**
