### PR TITLE
Preranap1-issue1294-introduction

### PR DESCRIPTION
**Pull request by preranap1**
reordered sections to add introduction at the beginning of the chapter

### CODE REVIEW

**Review by harizhisham — APPROVED** [review]
This makes more sense to put at the start of the chapter. Gives the reader an overview of the 7 steps in viz before jumping into the nitty gritty. Good work! I'll approve and merge

**Comment by harizhisham** [comment]
JK I can't merge.

**Comment by preranap1** [comment]
LOL! Thanks for approving though!

**Comment by harizhisham** [comment]
Found the mistake @preranap1, you want to merge into contributions instead of master.

**Comment by preranap1** [comment]
Thanks for pointing this out!! I changed the base to contributions..
You can now merge! :D

**Comment by harizhisham** [comment]
nice. merged! thanks

**Pull request merged**
