### PR TITLE
Update 06-process.Rmd

### PR DESCRIPTION
**Pull request by Psharma2193**
Contributed Case study on Marketing Analytics as proposed in Issue #1247

### CODE REVIEW

**Review by VikitaNayak — APPROVED** [review]
looks good now! Thanks for updating it

**Comment by gauravhassija** [comment]
Finally able to merge! Thanks for updating

**Comment by gauravhassija** [comment]
I found another interesting article that explains more about the audience
https://depictdatastudio.com/data-visualization-design-process-step-by-step-guide-for-beginners/

I will try and add these points to the Important Prerequisites

**Comment by VikitaNayak** [comment]
Yes, this is good. can be added!

**Pull request merged**
