### PR TITLE
1194-rlwy: Adjust image caption alignment and resolve broken image

### PR DESCRIPTION
**Pull request by rlwy**
Fixed for issue #1194 :
- Moved image caption for source to new line
- image path for Time Series Chart Using Line.

### CODE REVIEW

**Comment by preranap1** [comment]
Hi @rlwy the changes look good but I am not sure if the png files were uploaded in this commit. Can you please confirm if you added new png files or if you gave the right reference to the files?

**Comment by rlwy** [comment]
> Hi @rlwy the changes look good but I am not sure if the png files were uploaded in this commit. Can you please confirm if you added new png files or if you gave the right reference to the files?

Hey @preranap1 the png file has been in the images folder all along. The reason the image was broken was because there was a typo in the .Rmd file. Unfortunately, I am unable to compile the book due to issues in the book.bib file (from all our recent Pull Requests), so I did not upload a new version of the exported book in the docs folder.

**Comment by syragrg** [comment]
changes look good!

**Review by syragrg — APPROVED** [review]
changes look good!

**Review by Psharma2193 — APPROVED** [review]
The changes look good to me.

**Pull request merged**
