### PR TITLE
Vn issue 1133

### PR DESCRIPTION
**Pull request by VikitaNayak**

### CODE REVIEW

**Comment by VikitaNayak** [comment]
@mschermann Hello Professor,
I have added the references in book.bib and content to the fundamentals.rmd file. I am getting 'conflicts' for book.bib. I am not sure why there is a conflict .

Can you please help me understand the cause.

Thanks,
Vikita

**Comment by VikitaNayak** [comment]
Thanks!

**Comment by strivedi2** [comment]
are you able to see images in you rendering of the file?

**Comment by VikitaNayak** [comment]
Yes!

**Pull request merged**
