### PR TITLE
835: Fixed citation error and table width for section 2.1

### PR DESCRIPTION
**Pull request by rlwy**
Fixes issue #835.

### CODE REVIEW

**Comment by Cindyli0310** [comment]
> Fixes issue #835.
Hi @rlwy ,thanks a lot for sharing the correct citation and format. It is very important that I can click the correct link.

**Review by phoenixren — COMMENTED** [review]
Thank you and good work to correct the citation error.

**Review by pragyansharma24 — APPROVED** [review]
These changes are good!

**Comment by mschermann** [comment]
Next time, please merge the PR, too.

**Pull request merged**
