### PR TITLE
Fix 5.3.6 Bar Charts: vague graph problem 

### PR DESCRIPTION
**Pull request by Cindyli0310**
I changed the vague graph  to a clearer one.

### CODE REVIEW

**Comment by mayjai** [comment]
Hi @Cindyli0310 there seems to be conflicts that must be resolved in this pull request.

**Review by mayjai — COMMENTED** [review]
Hi @Cindyli0310 there seems to be conflicts that must be resolved.

**Comment by Cindyli0310** [comment]
@mayjai Hi,I think the conflict comes from I accidentally delete the 02-fundamental.rmd. I revert the change.So please help me review again. Thanks a lot for your reminding.

**Review by mayjai — APPROVED** [review]
Nice job resolving the conflict.

**Pull request merged**
