### PR TITLE
Updated Map section in pattens.rm

### PR DESCRIPTION
**Pull request by preranap1**
added popular techniques to visualize data in maps

### CODE REVIEW

**Comment by harizhisham** [comment]
Awesome! I like this addition to explain different types of map charts. 

Is there a reference you used to get these maps? Would be nice to add the reference.

**Comment by preranap1** [comment]
@harizhisham Thanks! I have added references at the beginning of the section and referenced them from the book.bib file. Had forgotten to add '@' before the references but have changed that now.
Let me know if you are able to see these changes.

**Comment by harizhisham** [comment]
Nice I see them. Will merge and close!

**Review by harizhisham — APPROVED** [review]
Looks good!

**Pull request merged**
