### PR TITLE
Format Fix For the case study

### PR DESCRIPTION
**Pull request by VikitaNayak**
In this pull request, I have made the format of the case study consistent for three topics discussed in it.

### CODE REVIEW

**Comment by VikitaNayak** [comment]
@Psharma2193 @gauravhassija The conflict has been resolved now. Free feel to review.

**Review by gary-boop — CHANGES_REQUESTED** [review]
The changes are good, there is a small typo on line 251 in the word 'sources'

**Review by kwright76 — DISMISSED** [review]

**Review by VikitaNayak — COMMENTED** [review]
The conflicts are resolved now

**Review by gary-boop — APPROVED** [review]

**Review by Psharma2193 — APPROVED** [review]
The changes look good!

**Comment by gauravhassija** [comment]
Changes are good

**Pull request merged**
