### PR TITLE
Fix issue #1389

### PR DESCRIPTION
**Pull request by Cindyli0310**
Fixed issue Added more graphs and platform links.

### CODE REVIEW

**Comment by mschermann** [comment]
@Cindyli0310 Please find reviewer and merge.

**Comment by preranap1** [comment]
Hey!
The changes seem okay to me but for some reason I am not able to open the process.rmd and resolve these conflicts.

**Review by JinjinJanelle — DISMISSED** [review]
Great job adding supporting graphs!

**Comment by XZou0803** [comment]
Hi All, I resolved the conflicts and it now can be merged.

**Review by XZou0803 — APPROVED** [review]

**Pull request merged**
